name: CI-test

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  NODE_OPTIONS: '--max_old_space_size=4096'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially  or in parallel
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: blah 
        run: |
          gh extension install actions/gh-actions-cache
      
