name: Running AutoTest

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  NODE_OPTIONS: '--max_old_space_size=4096'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially  or in parallel
jobs:
  auto-test:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Run autotest
        shell: bash
        run: |
          env
          exit 1
        
      
