name: Running AutoTest Ganesha

on:
  workflow_call:
    inputs:
      foo:
        description: "The reference point"
        required: true
        type: string
  workflow_dispatch:
  repository_dispatch:
  workflow_run:
  

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  NODE_OPTIONS: '--max_old_space_size=4096'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially  or in parallel
jobs:
  auto-test:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Run autotest
        env:
          PAYLOAD: ${{ github.event.client_payload.foo }}
        shell: bash
        run: |
          env
          exit 0
        
      
